name: vaultify
description: A cool flutter app by uncool corpses
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flex_seed_scheme: ^1.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^11.1.4
  heroicons: ^0.9.0
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/
  - assets/images/
  - assets/fonts/   